// PWA /manifest.webmanifest handler.
// Inlines the manifest directly so no fs / JSON import resolution is
// required at worker runtime. Kept in sync with ../manifest.json which
// remains the canonical source — this file is generated by build step.

// eslint-disable-next-line quotes
const MANIFEST = {"name":"IronWake — Systems that answer","short_name":"IronWake","description":"Operational workflow mapping and implementation for service businesses, with provider-dependent capabilities disclosed before activation.","start_url":"/","display":"standalone","background_color":"#f5f3ee","theme_color":"#f5f3ee","icons":[{"src":"/icon.svg","sizes":"any","type":"image/svg+xml","purpose":"any"},{"src":"/apple-icon.svg","sizes":"180x180","type":"image/svg+xml","purpose":"any maskable"},{"src":"/og-default.svg","sizes":"1200x630","type":"image/svg+xml","purpose":"any"}]};

export const dynamic = 'force-static';

if (!MANIFEST.name) {
  throw new Error('inlined manifest is missing required "name" field');
}

export function GET() {
  return new Response(JSON.stringify(MANIFEST), {
    headers: {
      'content-type': 'application/manifest+json',
      'cache-control': 'public, max-age=300, must-revalidate'
    }
  });
}
