import './globals.css';
import { SiteFooter } from './components/SiteFooter';
import FloatingActions from './components/FloatingActions';
import { ScrollToTop } from './components/ScrollToTop';
import { CookieBanner } from './components/CookieBanner';
import { ScrollProgress } from './components/motion';

// ponytail: PRODUCTION_CANONICAL_ORIGIN is the one source of truth for the canonical
// host. Every public-facing URL (metadataBase, sitemap, robots, JSON-LD) must derive
// from this constant. NEXT_PUBLIC_SITE_URL is an opt-in override for preview/local
// environments; in production it must be unset or equal to PRODUCTION_CANONICAL_ORIGIN.
// Changing this constant requires a full re-deploy + Search Console re-submission.
const PRODUCTION_CANONICAL_ORIGIN = 'https://ironwake.dev';
const FALLBACK_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || PRODUCTION_CANONICAL_ORIGIN;

export const metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || PRODUCTION_CANONICAL_ORIGIN),
  title: { default: 'IronWake — Systems that answer', template: '%s' },
  description: 'IronWake helps service businesses map and repair leaks across inquiry, booking, follow-up, and reception workflows.',
  robots: { index: true, follow: true },
  alternates: { canonical: './' }, // ponytail: './' lets Next.js auto-resolve canonical per route from metadataBase
  // ponytail: favicon + apple-touch-icon. apple points at /apple-icon.png — Next.js auto-route from app/apple-icon.png (the rasterized 180x180 PNG. The SVG source lives at app/apple-icon.svg and is regenerated by scripts/build_icons.mjs).
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
    apple: [{ url: '/apple-icon.svg', type: 'image/svg+xml', sizes: '180x180' }]
  },
  openGraph: {
    title: 'IronWake — Systems that answer',
    description: 'IronWake maps operational systems for clearer enquiry, booking, follow-up, and reception handoffs.',
    type: 'website',
    siteName: 'IronWake',
    url: './',
    images: [{ url: '/og-default.svg', width: 1200, height: 630, alt: 'IronWake — Systems that answer' }]
  },
  twitter: { card: 'summary_large_image', title: 'IronWake — Systems that answer', description: 'IronWake maps operational systems for clearer enquiry, booking, follow-up, and reception handoffs.', images: ['/og-default.svg'] }
};

export const viewport = {
  themeColor: '#F3F5F7',
};

// ponytail: Next.js requires error boundaries as dedicated files, not logic inside a
// Server Component layout — see app/error.js (segment) and app/global-error.js (root).
// Both stay inert until SENTRY_DSN/NEXT_PUBLIC_SENTRY_DSN are configured.
// ponytail: JSON-LD canonical URL uses the same FALLBACK_SITE_URL constant as metadataBase so structured data agrees with sitemap/robots.

export default function RootLayout({ children }) {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || PRODUCTION_CANONICAL_ORIGIN;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Organization', name: 'IronWake', url: siteUrl, description: 'IronWake maps operational systems for clearer enquiry, booking, follow-up, and reception handoffs.', founder: { '@type': 'Person', name: 'Revanth Nunna' }, areaServed: 'IN', sameAs: ['https://www.instagram.com/ironwake.dev/'] },
    { '@type': 'WebSite', name: 'IronWake', url: siteUrl },
    { '@type': 'Service', name: 'Business Leak Audit', url: `${siteUrl}/audit`, description: 'A review identifying where your enquiry, booking, or follow-up process loses momentum.' },
    { '@type': 'Service', name: 'Missed Lead Recovery', url: `${siteUrl}/systems/missed-lead-recovery`, description: 'Capture every enquiry to a durable record before any notification runs.' },
    { '@type': 'Service', name: 'Booking Certainty', url: `${siteUrl}/systems/booking-control`, description: 'Separate booking requests from confirmed appointments.' },
    { '@type': 'Service', name: 'AI Receptionist Planning', url: `${siteUrl}/systems/ai-receptionist`, description: 'Planning requirements for a disclosed, human-supervised first-response build. The IronWake site assistant is live and model-backed; a client receptionist deployment requires separately scoped provider integration.' },
    { '@type': 'ItemList', name: 'IronWake Systems', itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Missed Lead Recovery', url: `${siteUrl}/systems/missed-lead-recovery` },
      { '@type': 'ListItem', position: 2, name: 'Booking Certainty', url: `${siteUrl}/systems/booking-control` },
      { '@type': 'ListItem', position: 3, name: 'Trust and Lead Capture', url: `${siteUrl}/systems/trust-lead-capture` },
      { '@type': 'ListItem', position: 4, name: 'AI Receptionist', url: `${siteUrl}/systems/ai-receptionist` }
    ]}
  ]};
  return <html lang="en"><body><a className="skip-link" href="#main-content">Skip to main content</a><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><ScrollProgress /><main id="main-content" tabIndex={-1}>{children}</main><SiteFooter /><FloatingActions /><CookieBanner /><ScrollToTop /></body></html>;
}
