import { SiteFooter } from './components/SiteFooter';
import { SiteHeader } from './components/SiteHeader';

const systems = [
  ['01 / inquiry integrity', 'Missed Lead Recovery', 'Make dropped enquiries visible before adding another tool.'],
  ['02 / booking control', 'Booking Certainty', 'Map the handoff from interest to a named next action.'],
  ['03 / reception layer', 'AI Receptionist', 'A future system category; provider proof and scope stay explicit.']
];

export default function Home() {
  return <main className="shell">
    <SiteHeader />
    <section className="hero"><span className="eyebrow">Systems for service businesses</span><h1>Stop letting good leads disappear between inquiry and follow-up.</h1><p>IronWake maps the gaps between enquiry, booking, response and follow-up so the next action stays visible, owned, and reviewable.</p><div className="signal-rail" role="group" aria-label="Operating flow: inquiry to owner to next action"><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Inquiry</span></div><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Owner</span></div><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Next action</span></div><span className="signal-rail-pulse" aria-hidden="true" /></div><div className="hero-actions"><a className="button" href="/audit">Request a Business Leak Audit</a><a className="button secondary" href="/systems">Explore systems</a></div><aside className="status-card" aria-label="Operating status"><span className="micro">System state / private</span><dl><div><dt>Inquiry record</dt><dd>Saved first</dd></div><div><dt>Follow-up</dt><dd>Human review</dd></div><div><dt>Provider state</dt><dd>Explicit</dd></div></dl></aside></section>
    <section className="section intro"><span className="eyebrow">Systems index</span><h2>Modular systems for lead integrity.</h2><div className="system-grid">{systems.map(([label, title, text]) => <article className="system-card" key={title}><span className="micro">{label}</span><h3>{title}</h3><p>{text}</p><span className="card-link">Explore with an audit →</span></article>)}</div></section>
    <section className="section"><span className="eyebrow">Demonstration work</span><h2>Case engineering.</h2><div className="case-grid"><article className="case-large"><div className="case-art" /><div className="case-copy"><span className="micro">Portfolio demonstration</span><h3>RapidPulse Response</h3><p>Emergency-service workflow demonstration. This is capability proof, not a client result.</p></div></article><div className="case-stack"><article><span className="micro">Portfolio demonstration</span><h3>DentaCare Intake</h3><p>Clinic intake-flow demonstration, shown without live provider claims.</p></article><article><span className="micro">Portfolio demonstration</span><h3>Atelier Safe</h3><p>Consultation-system demonstration with no implied booking connection.</p></article></div></div></section>
    <section className="section"><div className="progress-grid"><div><span className="eyebrow">Operating model</span><h3>Inspectable progress.</h3><p>We do not sell theatre. We make operational decisions inspectable.</p></div><div className="progress-list"><div><span>01 / visibility</span><strong>Capture existing leaks</strong></div><div><span>02 / ownership</span><strong>Clarify the next action</strong></div><div><span>03 / control</span><strong>Review automation before relying on it</strong></div></div></div></section>
    <section className="section"><span className="eyebrow">Industrial focus</span><h2>Built around high-intent conversations.</h2><div className="industry-grid"><article className="industry-card"><span className="micro">01 / services</span><h3>Emergency Services</h3><p>For teams where response ownership can affect the next conversation.</p></article><article className="industry-card"><span className="micro">02 / care</span><h3>Private Clinics</h3><p>For structured enquiry and booking pathways that need careful review.</p></article><article className="industry-card"><span className="micro">03 / appointments</span><h3>Salons & Spas</h3><p>For consultation-led businesses where the experience continues after enquiry.</p></article></div></section>
    <section className="journey"><span className="eyebrow">Operational lens</span><h2>The technical journey.</h2><div className="journey-grid"><article><span className="micro">01 / audit</span><h3>Map the path</h3><p>See where a visitor loses context or a team loses ownership.</p></article><article><span className="micro">02 / ownership</span><h3>Name the next action</h3><p>Make a real person and a real follow-up state visible.</p></article><article><span className="micro">03 / systems</span><h3>Use the smallest system</h3><p>Prefer an understandable fix over a bigger stack.</p></article><article><span className="micro">04 / review</span><h3>Verify the state</h3><p>Do not label a provider, booking, or outcome complete without proof.</p></article></div></section>
    <section className="section disclosure"><div><span className="eyebrow">Truth standard</span><h3>Detailed disclosure.</h3></div><div className="disclosure-box">IronWake labels work as a DEMONSTRATION until independent client or provider evidence supports a stronger claim. Public pricing, provider status, outcomes, and integrations are omitted until they are verified.</div></section>
    <section className="section founder"><div className="founder-mark">IRONWAKE<br />SYSTEMS PRACTICE</div><div><span className="eyebrow">Founder</span><h2>Revanth Nunna</h2><p>IronWake is a founder-led systems practice. The work starts by making one business-critical handoff visible, then making the next action clearer.</p><span className="micro">Founder, IronWake</span></div></section>
    <SiteFooter />
  </main>;
}
