import { SiteFooter } from './components/SiteFooter';
import { SiteHeader } from './components/SiteHeader';
import { MotionReveal } from './components/MotionReveal';
import { WorkflowDemo } from './components/WorkflowDemo';
import { DashboardDemo } from './components/DashboardDemo';
import { InteractiveLeadJourney } from './components/InteractiveLeadJourney';

const systems = [
  ['01 / inquiry integrity', 'Missed Lead Recovery', 'See where an enquiry stalls, who owns it, and what should happen next.', '/systems/missed-lead-recovery'],
  ['02 / booking control', 'Booking Certainty', 'Separate a booking request from a confirmed appointment so nobody assumes the wrong state.', '/systems/booking-control'],
  ['03 / trust layer', 'Trust + Lead Capture', 'Capture enquiries on a conversion-optimised intake that persists first, notifies second.', '/systems/trust-lead-capture'],
  ['04 / reception layer', 'AI Receptionist', 'A disclosed, human-supervised first response. Capability is built; live telephony waits on a verified provider account.', '/systems/ai-receptionist']
];


export function generateMetadata() {
  return {
    title: 'IronWake — Stop losing leads between enquiry and follow-up',
    description: 'IronWake builds operational systems that capture enquiries, assign ownership, control follow-up and show business owners exactly what happens next.',
    openGraph: {
      title: 'IronWake — Stop losing leads between enquiry and follow-up',
      description: 'Operational systems for service businesses. Capture every enquiry, assign a named owner, make the next action visible.',
      type: 'website',
      siteName: 'IronWake',
    },
  };
}

export default function Home() {
  return <main className="shell">
    <SiteHeader />
    <section className="hero"><span className="eyebrow">Systems practice for service businesses</span><h1>Stop losing leads between enquiry and follow-up.</h1><p>IronWake maps where your enquiry, booking, or follow-up process loses momentum, then builds the smallest operational system that makes the next step visible and owned. Starts with a ₹799 / $29 diagnostic.</p><WorkflowDemo /><div className="signal-rail" role="group" aria-label="Operating flow: inquiry to owner to next action"><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Inquiry</span></div><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Owner</span></div><div className="signal-rail-node"><span className="signal-rail-dot" aria-hidden="true" /><span className="signal-rail-label">Next action</span></div><span className="signal-rail-pulse" aria-hidden="true" /></div><div className="hero-actions"><a className="button" href="/audit">Book Diagnostic</a><a className="button secondary" href="/pricing">See pricing</a></div><aside className="status-card" aria-label="Operating status"><span className="micro">The operating rule</span><dl><div><dt>Enquiry</dt><dd>Recorded</dd></div><div><dt>Owner</dt><dd>Named</dd></div><div><dt>Next step</dt><dd>Visible</dd></div></dl></aside></section>
    <MotionReveal stagger><section className="section intro"><span className="eyebrow">Choose the problem</span><h2>Start with the handoff that is costing attention.</h2><div className="system-grid">{systems.map(([label, title, text, href]) => <a className="system-card" href={href} key={title}><span className="micro">{label}</span><h3>{title}</h3><p>{text}</p><span className="card-link">Open this system <span aria-hidden="true">→</span></span></a>)}</div></section></MotionReveal>
    <MotionReveal stagger><section className="section"><span className="eyebrow">Interactive demonstrations</span><h2>See the workflow, not a vague promise.</h2><div className="case-grid"><a className="case-large" href="/work/rapidpulse"><div className="case-art" role="img" aria-label="Abstract inquiry-to-action flow" /><div className="case-copy"><span className="micro">Portfolio demonstration</span><h2>RapidPulse Response</h2><p className="case-metric">Demonstration: inquiry-to-ownership handoff with queued notification.</p><p>Follow an urgent enquiry from first contact to named ownership.</p><span className="card-link">Open the demonstration →</span></div></a><div className="case-stack"><a href="/work/dentacare-pro"><article><span className="micro">Portfolio demonstration</span><h2>DentaCare Intake</h2><p className="case-metric">Demonstration: validated intake to reviewed booking request.</p><p>See how a clinic-style request becomes a reviewed next step.</p><span className="card-link">Open demonstration →</span></article></a><a href="/work/atelier"><article><span className="micro">Portfolio demonstration</span><h2>Atelier Safe</h2><p className="case-metric">Demonstration: consultation capture with named follow-up owner.</p><p>See how consultation interest stays owned after the first enquiry.</p><span className="card-link">Open demonstration →</span></article></a></div></div></section></MotionReveal>
    <MotionReveal><section className="section"><div className="progress-grid"><div><span className="eyebrow">Operating model</span><h3>Inspectable progress.</h3><p>We do not sell theatre. We make operational decisions inspectable.</p></div><div className="progress-list"><div><span>01 / visibility</span><strong>Capture existing leaks</strong></div><div><span>02 / ownership</span><strong>Clarify the next action</strong></div><div><span>03 / control</span><strong>Review automation before relying on it</strong></div></div></div></section></MotionReveal>
    <DashboardDemo />
    <InteractiveLeadJourney />
    <MotionReveal stagger><section className="section"><span className="eyebrow">Choose your industry</span><h2>Different businesses lose enquiries in different places.</h2><div className="industry-grid"><a className="industry-card" href="/industries/home-services"><span className="micro">01 / home services</span><h3>Home Services</h3><p>Keep missed calls and urgent requests from ending without a callback owner.</p><span className="card-link">View industry →</span></a><a className="industry-card" href="/industries/dental-clinics"><span className="micro">02 / front desk</span><h3>Dental & Private Clinics</h3><p>Keep phone, walk-in, and online requests in one reviewable intake path.</p><span className="card-link">View industry →</span></a><a className="industry-card" href="/industries/salons-spas"><span className="micro">03 / appointments</span><h3>Salons & Spas</h3><p>Make sure consultation interest receives a clear follow-up before it cools.</p><span className="card-link">View industry →</span></a></div></section></MotionReveal>
    <MotionReveal><section className="journey"><span className="eyebrow">Operational lens</span><h2>The technical journey.</h2><div className="journey-grid"><article><span className="micro">01 / audit</span><h3>Map the path</h3><p>See where a visitor loses context or a team loses ownership.</p></article><article><span className="micro">02 / ownership</span><h3>Name the next action</h3><p>Make a real person and a real follow-up state visible.</p></article><article><span className="micro">03 / systems</span><h3>Use the smallest system</h3><p>Prefer an understandable fix over a bigger stack.</p></article><article><span className="micro">04 / review</span><h3>Verify the state</h3><p>Do not label a provider, booking, or outcome complete without proof.</p></article></div></section></MotionReveal>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: [
        { '@type': 'Question', name: 'What does IronWake do?', acceptedAnswer: { '@type': 'Answer', text: 'IronWake builds operational systems that capture enquiries, assign ownership, control follow-up and show business owners exactly what happens next.' }},
        { '@type': 'Question', name: 'How much does IronWake cost?', acceptedAnswer: { '@type': 'Answer', text: 'IronWake publishes tiered offer pricing on /pricing. Each engagement starts with the Business Leak Audit offer tier shown there.' }},
        { '@type': 'Question', name: 'Is IronWake an AI chatbot?', acceptedAnswer: { '@type': 'Answer', text: 'No. IronWake is a systems practice that maps where your process loses momentum and implements the smallest system to fix it.' }},
        { '@type': 'Question', name: 'What happens after the audit?', acceptedAnswer: { '@type': 'Answer', text: 'You receive a written review identifying where your process loses momentum, what is verified versus assumed, and the smallest next step to fix it.' }},
      ]
    })}} />
    <section className="section"><span className="eyebrow">Common questions</span><h2>What business owners ask.</h2><div className="faq-grid">{[['What does IronWake actually do?', 'We build operational systems that capture enquiries, assign ownership, control follow-up, and show you exactly what happens next — so no lead is lost between first contact and a booked outcome.'], ['Is this a chatbot or AI agent?', 'No. IronWake is a systems practice. We map where your enquiry, booking, or follow-up process loses momentum, then implement the smallest system that makes the next step visible and owned.'], ['How much does it cost?', 'Published offer tiers are listed on /pricing. Each engagement starts with the Business Leak Audit tier shown there. Implementation costs depend on confirmed scope and are quoted after the audit.'], ['Do you integrate with my existing tools?', 'Where a verified provider connection exists, yes. Where it does not, we build the workflow first and connect providers when they are confirmed. We never claim an integration before it is proven.'], ['What happens after the audit?', 'You receive a written review identifying where your process loses momentum, what is verified versus assumed, and the smallest next step to fix it. No obligation, no pressure.']].map(([q, a]) => <details key={q} className="faq-item"><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <MotionReveal><section className="section disclosure"><div><span className="eyebrow">Truth standard</span><h3>Verified claims only.</h3><p>IronWake labels work as a demonstration until independent evidence supports a stronger claim. Published prices are confirmed offer tiers. Provider status and client outcomes are omitted until verified.</p></div><div className="disclosure-box">No testimonial, metric, benchmark, or provider status is published without reproducible evidence and named approval.</div></section></MotionReveal>
    <section className="section founder"><div className="founder-mark">IRONWAKE<br />SYSTEMS PRACTICE</div><div><span className="eyebrow">Founder</span><h2>Revanth Nunna</h2><p>IronWake is a founder-led systems practice for service businesses. The work begins with one real enquiry or booking handoff and improves it without hiding uncertainty behind software.</p><span className="micro">Founder, IronWake</span></div></section>
    <SiteFooter />
  </main>;
}
