import { SiteFooter } from '../components/SiteFooter';
import { SiteHeader } from '../components/SiteHeader';

import { organizationLd, breadcrumbLd } from '../lib/seo.mjs';
import { canonicalUrl } from '../lib/seo.mjs';
export const metadata = {
  title: 'Terms — IronWake',
  description: 'How the published setup prices, scope requests, customer accounts, proposals, and provider costs work on this site, and what is not yet an automatic ordering flow.',
  alternates: { canonical: canonicalUrl("/terms") },
};

export default function TermsPage() {
  return <main className="shell">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationLd()) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd([
              { name: "Home", path: "/" },
              { name: "Terms", path: "/terms" },
        ])) }} />

    <SiteHeader />
    <section className="hero compact">
      <span className="eyebrow">IronWake / Terms</span>
      <h1>What these terms cover right now.</h1>
      <p>This site is a capability demo running in pre-launch mode. The published setup prices are real, the scope request is a real form, customer accounts are real, and the chatbot is a real AI — but proposals and contracts are handled by email until the first client is onboarded.</p>
    </section>

    <section className="surface">
      <h2>Setup prices on the Pricing page</h2>
      <p>The five offer prices listed on the <a href="/pricing">Pricing</a> page are the published setup cost for each scope. They are not generated by an automatic checkout. Currency is fixed in INR for India and USD for International; there is no in-page FX conversion.</p>
      <p>Provider, domain, and third-party usage costs are separate and are itemised in the proposal after a scope request, not on this site.</p>
    </section>

    <section className="surface">
      <h2>Scope request flow</h2>
      <p>Submitting the audit or booking form sends a real record to our operator queue. We treat it as a request to scope work, not as a binding purchase. No charge is taken on the website today.</p>
    </section>

    <section className="surface">
      <h2>Customer accounts</h2>
      <p>You can create a free IronWake account at <a href="/signup">/signup</a>. The account lets you save Ask IronWake conversations, keep your audit and booking history in one place, and return to either without re-entering your details.</p>
      <p>Customer accounts are separate from the private operator dashboard. A customer account never grants access to the owner CRM or any internal tooling, even if the same email is ever shared.</p>
      <p>You can update your display name or sign out at any time from <a href="/account">/account</a>. Password changes are handled by Supabase Auth via <a href="/forgot-password">/forgot-password</a>.</p>
    </section>

    <section className="surface">
      <h2>Ask IronWake chatbot</h2>
      <p>The chatbot on this site is a real AI assistant grounded in the published IronWake knowledge. It is scoped to IronWake business questions; it refuses unrelated coding, hacking, or secret-extraction requests. Conversations with the chatbot are anonymous by default. If you create an account and chat while signed in, your conversation is saved to your account and can be reviewed from <a href="/account">/account</a>.</p>
      <p>The chatbot is not a deployed receptionist for your business. Building a real AI receptionist for a client requires a separately scoped provider build with its own proposal.</p>
    </section>

    <section className="surface">
      <h2>Proposal, contract, and payment</h2>
      <p>Once a request is reviewed, we send a written proposal by email. The proposal, when accepted by written reply, is the contract. Payment terms, milestones, and the small print (delivery window, what is in scope, what is not) all live in that proposal.</p>
      <p>Until the first client is onboarded, payment is handled by manual bank transfer or UPI against the proposal. There is no automatic online checkout on this site yet.</p>
    </section>

    <section className="surface">
      <h2>What these terms do not yet cover</h2>
      <ul>
        <li>Tax treatment (GST, VAT, sales tax) — applied per the proposal and the buyer's jurisdiction; the site does not collect tax today.</li>
        <li>Refunds — handled per the proposal; the website has no automatic refund mechanism.</li>
        <li>Standard form contract — to be reviewed and added before the first paid engagement.</li>
      </ul>
    </section>

    <section className="surface">
      <h2>Entity and contact</h2>
      <p>This site is operated by the founder of IronWake. No separate legal entity is registered behind it yet; that will be added before the first paying client is onboarded. The current operator contact is <a href="mailto:ironwake.dev@gmail.com">ironwake.dev@gmail.com</a>.</p>
    </section>

    <SiteFooter />
  </main>;
}
